In [1]:
import pandas as pd
df = pd.read_csv("housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [2]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [3]:
df['total_bedrooms'] = df['total_bedrooms'] / df['households']
df['total_rooms'] = df['total_rooms'] / df['households']
df['population'] = df['population'] / df['households']

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,6.984127,1.023810,2.555556,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,6.238137,0.971880,2.109842,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,8.288136,1.073446,2.802260,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,5.817352,1.073059,2.547945,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,6.281853,1.081081,2.181467,259.0,3.8462,342200.0,NEAR BAY

In [4]:
df['total_bedrooms'].value_counts()

total_bedrooms
1.000000    288
1.125000     29
1.058824     26
1.100000     25
1.083333     25
           ...
1.020902      1
1.141204      1
1.148256      1
1.171920      1
1.162264      1
Name: count, Length: 14121, dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [6]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean())
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
import joblib

In [8]:
x = df.drop('median_house_value', axis=1)
y = df['median_house_value']

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [10]:
sc = StandardScaler()
oe = OneHotEncoder()

In [11]:
numerical_features = x_train.select_dtypes(include='float').columns
cat_features = x_train.select_dtypes(include='str').columns

In [12]:
preprocessor = ColumnTransformer(
    transformers = [
    ('cat', oe , cat_features),
    ('num', sc, numerical_features)
])

In [13]:
model = make_pipeline(preprocessor, LinearRegression())
model.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  Index(['ocean_proximity'], dtype='str')),
                                                 ('num', StandardScaler(),
                                                  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='str'))])),
                ('linearregression', LinearRegression())])

In [14]:
predictions = model.predict(x_test)
mse = mean_squared_error(y_test, predictions)

In [15]:
import numpy as np
print('MSE : ', np.sqrt(mse) )

MSE :  70964.62516120863

In [16]:
joblib.dump(model, 'u16_regressiya_houses.joblib') # bu yerda malumotni saqlab qoyyabmiz ozgaruvchhhi nommini ozimiz tanlaymiz

['u16_regressiya_houses.joblib']

In [17]:
loaded_model = joblib.load('u16_regressiya_houses.joblib') # bu yerda faylni chiqarib olyabmiz

In [18]:
import pandas as pd

new_house = pd.DataFrame({
    'longitude': [-122.23, -118.25, -121.89, -117.16, -119.70, -122.42],
    'latitude': [37.77, 34.05, 37.33, 32.71, 34.44, 37.77],
    'housing_median_age': [35, 42, 15, 52, 28, 10],
    'total_rooms': [2500, 1800, 3200, 4200, 1500, 5000],
    'total_bedrooms': [485, 360, 590, 810, 300, 950],
    'population': [1100, 900, 1600, 2100, 700, 2500],
    'households': [420, 330, 580, 780, 260, 920],
    'median_income': [6.5, 4.2, 8.1, 3.8, 5.5, 9.3],
    'ocean_proximity': ['NEAR OCEAN', '<1H OCEAN', 'NEAR BAY', 'INLAND', '<1H OCEAN', 'NEAR OCEAN']
})

In [19]:
 
prediction = loaded_model.predict(new_house)
print('house : ',prediction)

house :  [4763477.87773146 3843180.89649963 4589543.22682555 7296158.97368468
 3328180.98380934 8260894.10078544]